server:
  port: 8087

spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/client-db'

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: @project.name@
